apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
  default.conf: |
    events {
      worker_connections 1024;
    }
    http {
      upstream server {
          server nginx-service;
    }
      server {
          listen 80;

          server_name localhost;

          location / {
              root /usr/share/nginx/html;
              index index.html;
          }

          location /api/ {
              proxy_pass http://server;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection 'upgrade';
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
          }
      }
    }
